import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { buildGradebook } from "./gradebook.service.js";
import { normalizeGradebookPolicy, aggregateQuizAttempts, calculateGradebookTotal, normalizeAnnotations, canResubmit } from "./lmsWorkflowPolicy.service.js";

test("gradebook policy distinguishes missing grades, actual zero and quiz attempt strategy", () => {
  const policy=normalizeGradebookPolicy({weights:{assignment:50,quiz:40,attendance:10},quizStrategy:"best",missingPolicy:"exclude",passMark:60});
  assert.equal(calculateGradebookTotal({assignment:[100,null,0],quiz:[],attendance:[]},policy).total,50);
  assert.equal(calculateGradebookTotal({assignment:[100,null,0]}, {...policy,missingPolicy:"zero"}).total,33.33);
  assert.equal(calculateGradebookTotal({},policy).total,null);
  const attempts=[{id:1,attempt_number:1,score:9,max_score:10},{id:2,attempt_number:2,score:20,max_score:100}];
  assert.equal(aggregateQuizAttempts(attempts,"best"),90);
  assert.equal(aggregateQuizAttempts(attempts,"latest"),20);
  assert.equal(aggregateQuizAttempts(attempts,"average"),55);
  assert.throws(()=>normalizeGradebookPolicy({...policy,weights:{assignment:40,quiz:40,attendance:10}}));
  assert.throws(()=>normalizeAnnotations([{page:1,text:"bad",x:2,y:0.5}]));
  assert.equal(canResubmit({return_requested:true,resubmit_until:"2020-01-01"}),false);
});

test("LMS workflows execute against isolated PostgreSQL migrations", async (t) => {
  const db=new PGlite();
  t.after(()=>db.close());
  await db.exec(await fs.readFile("database/schema.sql","utf8"));
  const registry=await fs.readFile("run_sql.js","utf8");
  const migrations=[...registry.matchAll(/"database\/migrations\/[^"]+\.sql"/g)].map((m)=>JSON.parse(m[0]));
  for(const migration of migrations) await db.exec(await fs.readFile(migration,"utf8"));
  // These route tests use no listener, production DB or external network.
  process.env.DATABASE_URL="postgresql://unused:unused@127.0.0.1:1/test";
  const {pool}=await import("../db/connect.js");
  pool.query=(sql,params)=>db.query(sql,params);
  pool.connect=async()=>({query:(sql,params)=>db.query(sql,params),release(){}});
  process.env.BREVO_API_KEY="";
  const originalFetch=globalThis.fetch;
  globalThis.fetch=async()=>{throw new Error("Network is disabled in isolated workflow tests");};
  t.after(()=>{globalThis.fetch=originalFetch;});
  const assignments=(await import("../router/assignment.router.js")).default;
  const courses=(await import("../router/course.router.js")).default;
  const attendance=(await import("../router/attendance.router.js")).default;
  const reports=(await import("../router/report.router.js")).default;
  const support=(await import("../router/support.router.js")).default;
  const reminders=(await import("./assignmentDeadlineNotification.service.js")).processAssignmentDeadlineReminders;
  const invoke=async(router,method,path,{user,params={},query={},body={}}={})=>{
    const layer=router.stack.find((l)=>l.route?.path===path&&l.route.methods[method]);
    assert.ok(layer,`Missing route ${method} ${path}`);
    const res={statusCode:200,body:null,headers:{},status(code){this.statusCode=code;return this;},json(value){this.body=value;return this;},send(value){this.body=value;return this;},set(value){Object.assign(this.headers,value);return this;}};
    await layer.route.stack.at(-1).handle({user,params,query,body,ip:"127.0.0.1"},res,()=>{});
    return res;
  };
  const one=async(sql,params=[])=>(await db.query(sql,params)).rows[0];
  const teacher=await one("INSERT INTO users(username,email,role) VALUES ('teacher-test','teacher@example.test','creator') RETURNING *");
  const admin=await one("INSERT INTO users(username,email,role) VALUES ('admin-test','admin@example.test','admin') RETURNING *");
  const stranger=await one("INSERT INTO users(username,email,role) VALUES ('other-test','other@example.test','creator') RETURNING *");
  const student=await one("INSERT INTO users(username,email,role,is_management_managed,lms_account_status) VALUES ('student-test','student@example.test','user',TRUE,'active') RETURNING *");
  const course=await one("INSERT INTO courses(name,slug,author_id,is_published) VALUES ('Test Course','workflow-test',$1,TRUE) RETURNING *",[teacher.id]);
  const cls=await one("INSERT INTO live_classes(title,course_id,instructor_id) VALUES ('Test Class',$1,$2) RETURNING *",[course.id,teacher.id]);
  const session=await one("INSERT INTO class_sessions(live_class_id,title,start_time,end_time,status) VALUES ($1,'Session 1',NOW()-INTERVAL '2 hours',NOW()-INTERVAL '1 hour','ended') RETURNING *",[cls.id]);
  const session2=await one("INSERT INTO class_sessions(live_class_id,title,start_time,end_time,status) VALUES ($1,'Session 2',NOW()-INTERVAL '4 hours',NOW()-INTERVAL '3 hours','ended') RETURNING *",[cls.id]);
  await db.query("INSERT INTO class_enrollments(user_id,live_class_id) VALUES ($1,$2)",[student.id,cls.id]);
  await db.query("INSERT INTO lms_access_grants(user_id,course_id,access_status,valid_from,source_updated_at) VALUES ($1,$2,'active',NOW()-INTERVAL '1 day',NOW())",[student.id,course.id]);
  const assignment=await one("INSERT INTO assignments(title,course_id,live_class_id,class_session_id,instructor_id,due_date) VALUES ('Essay 1',$1,$2,$3,$4,NOW()-INTERVAL '1 hour') RETURNING *",[course.id,cls.id,session.id,teacher.id]);
  let submission;
  await t.test("assignment detail, personal deadline and submission execute without undefined variables",async()=>{
    let r=await invoke(assignments,"get","/:assignmentId",{user:student,params:{assignmentId:assignment.id}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    r=await invoke(assignments,"put","/teacher/accommodations",{user:teacher,body:{assessmentType:"assignment",assessmentId:assignment.id,userId:student.id,dueAt:new Date(Date.now()+72*3600000).toISOString(),extraTimeMinutes:0,reason:"Verified learner deadline accommodation"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    await reminders();
    assert.equal(Number((await one("SELECT COUNT(*) AS n FROM notifications WHERE event_type='assignment.overdue'")).n),0);
    r=await invoke(assignments,"post","/:id/submit",{user:student,params:{id:assignment.id},body:{contentText:"First version"}});
    assert.equal(r.statusCode,201,JSON.stringify(r.body));submission=r.body.data;
    assert.equal(submission.status,"submitted");
    r=await invoke(assignments,"post","/:id/submit",{user:student,params:{id:assignment.id},body:{contentText:"duplicate"}});
    assert.equal(r.statusCode,409);
  });
  await t.test("drafts stay private, publication and resubmission retain history and reject stale grading",async()=>{
    const params={submissionId:submission.id};
    let r=await invoke(assignments,"put","/submissions/:submissionId/draft",{user:teacher,params,body:{revision:1,score:8,feedbackText:"Draft only",annotations:[{page:1,text:"Fix this part",x:0.3,y:0.4}]}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    r=await invoke(assignments,"get","/submissions/:submissionId/history",{user:student,params});
    assert.equal(r.body.data.draft,null);assert.equal(r.body.data.grades.length,0);
    r=await invoke(assignments,"post","/submissions/:submissionId/grade",{user:teacher,params,body:{revision:1,score:8,feedbackText:"Published"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    r=await invoke(assignments,"post","/submissions/:submissionId/return",{user:teacher,params,body:{revision:1,reason:"Please revise the conclusion",resubmitUntil:new Date(Date.now()+86400000).toISOString()}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    r=await invoke(assignments,"post","/:id/submit",{user:student,params:{id:assignment.id},body:{contentText:"Second version"}});
    assert.equal(r.statusCode,201,JSON.stringify(r.body));assert.equal(r.body.data.revision,2);
    r=await invoke(assignments,"get","/:assignmentId",{user:student,params:{assignmentId:assignment.id}});
    assert.equal(r.body.data.score,null,"old revision grade must not become the new revision grade");
    r=await invoke(assignments,"post","/submissions/:submissionId/grade",{user:teacher,params,body:{revision:1,score:5,feedbackText:"stale"}});
    assert.equal(r.statusCode,409);
    r=await invoke(assignments,"post","/submissions/:submissionId/grade",{user:teacher,params,body:{revision:2,score:9,feedbackText:"Improved"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    r=await invoke(assignments,"get","/submissions/:submissionId/history",{user:teacher,params});
    assert.equal(r.body.data.revisions.length,1);assert.equal(r.body.data.revisions[0].snapshot.content_text,"First version");
    assert.equal(r.body.data.grades.length,2);
    r=await invoke(assignments,"post","/submissions/:submissionId/grade",{user:teacher,params,body:{revision:2,score:8,feedbackText:"regrade"}});
    assert.equal(r.statusCode,422,"published regrade needs a reason");
    r=await invoke(assignments,"get","/submissions/:submissionId/history",{user:stranger,params});
    assert.equal(r.statusCode,403);
  });
  await t.test("attendance review enforces reasons, separate reviewer and notifies requester",async()=>{
    await db.query("INSERT INTO class_attendance(session_id,user_id,status) VALUES ($1,$2,'absent')",[session.id,student.id]);
    let r=await invoke(attendance,"post","/amendments",{user:teacher,body:{sessionId:session.id,userId:student.id,requestedStatus:"present",reason:"Correction verified from class roster"}});
    assert.equal(r.statusCode,201,JSON.stringify(r.body));const id=r.body.data.id;
    r=await invoke(attendance,"get","/amendments",{user:admin,query:{status:"pending"}});
    assert.equal(r.body.data.length,1);
    r=await invoke(attendance,"post","/amendments/:amendmentId/review",{user:teacher,params:{amendmentId:id},body:{decision:"approved"}});
    assert.equal(r.statusCode,403);
    r=await invoke(attendance,"post","/amendments/:amendmentId/review",{user:admin,params:{amendmentId:id},body:{decision:"rejected",reviewNote:""}});
    assert.equal(r.statusCode,422);
    r=await invoke(attendance,"post","/amendments/:amendmentId/review",{user:admin,params:{amendmentId:id},body:{decision:"approved",reviewNote:"Checked teacher evidence"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    assert.equal((await one("SELECT status FROM class_attendance WHERE session_id=$1",[session.id])).status,"present");
  });
  await t.test("gradebook exports obey session scope, freeze results and require reopening before grading",async()=>{
    await db.query("INSERT INTO assignments(title,live_class_id,class_session_id,instructor_id) VALUES ('Session Two Task',$1,$2,$3)",[cls.id,session2.id,teacher.id]);
    let r=await invoke(reports,"get","/gradebook/export",{user:teacher,query:{classId:cls.id,sessionId:session.id,format:"csv"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));assert.ok(r.body.includes("Essay 1"));assert.ok(!r.body.includes("Session Two Task"));
    r=await invoke(reports,"get","/gradebook/export",{user:stranger,query:{classId:cls.id}});
    assert.equal(r.statusCode,403);
    r=await invoke(reports,"post","/gradebook/finalize",{user:teacher,body:{classId:cls.id}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    r=await invoke(assignments,"post","/submissions/:submissionId/grade",{user:teacher,params:{submissionId:submission.id},body:{revision:2,score:10,feedbackText:"new",changeReason:"Updated grading after review"}});
    assert.equal(r.statusCode,409);
    r=await invoke(reports,"get","/gradebook/my-result",{user:student,query:{classId:cls.id}});
    assert.equal(r.statusCode,200);assert.ok(r.body.data.total>0);
    r=await invoke(attendance,"post","/check",{user:teacher,body:{sessionId:session2.id,attendanceList:[{userId:student.id,status:"present"}]}});
    assert.equal(r.statusCode,409,"finalized gradebook must prevent a new attendance sheet");
    assert.match(r.body.message,/Sổ điểm đã chốt/);
    r=await invoke(reports,"post","/gradebook/reopen",{user:teacher,body:{classId:cls.id,reason:"Reopening for verified correction"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    assert.equal((await buildGradebook(db,cls.id,session.id)).activities.length,1);
  });
  await t.test("question bank supports editing, course sharing, blueprint sampling and ownership",async()=>{
    let r=await invoke(assignments,"post","/teacher/question-bank",{user:teacher,body:{courseId:course.id,questionText:"Question?",options:["A","B"],correctAnswer:0,points:1,explanation:"Because A",tags:["grammar"],difficulty:"easy",visibility:"course"}});
    assert.equal(r.statusCode,201,JSON.stringify(r.body));const id=r.body.data.id;
    r=await invoke(assignments,"put","/teacher/question-bank/:itemId",{user:teacher,params:{itemId:id},body:{questionText:"Updated question?",options:["A","B"],correctAnswer:1,points:2,explanation:"Because B",tags:["grammar"],difficulty:"easy",visibility:"course"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    r=await invoke(assignments,"post","/teacher/question-bank/sample",{user:teacher,body:{courseId:course.id,blueprint:{easy:1},tag:"grammar"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));assert.equal(r.body.data[0].correctAnswer,1);
    r=await invoke(assignments,"post","/teacher/question-bank/sample",{user:teacher,body:{courseId:course.id,blueprint:{easy:2}}});
    assert.equal(r.statusCode,422);
    r=await invoke(assignments,"get","/teacher/question-bank",{user:stranger,query:{courseId:course.id}});
    assert.equal(r.statusCode,403);
    await db.query("INSERT INTO class_teachers(live_class_id,teacher_id) VALUES ($1,$2)",[cls.id,stranger.id]);
    r=await invoke(courses,"get","/admin",{user:stranger});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    assert.ok(r.body.data.some((row)=>Number(row.id)===Number(course.id)),"assigned co-teacher must see the course selector");
    r=await invoke(assignments,"get","/teacher/question-bank",{user:stranger,query:{courseId:course.id}});
    assert.equal(r.body.data.length,1,"co-teacher may read shared course questions");
    r=await invoke(assignments,"delete","/teacher/question-bank/:itemId",{user:stranger,params:{itemId:id}});
    assert.equal(r.statusCode,403,"sharing does not permit deleting another teacher's question");
    r=await invoke(assignments,"post","/teacher/question-bank",{user:stranger,body:{courseId:course.id,questionText:"Private question?",options:["A","B"],correctAnswer:0,points:1,visibility:"private"}});
    assert.equal(r.statusCode,201,JSON.stringify(r.body));const privateId=r.body.data.id;
    r=await invoke(assignments,"get","/teacher/question-bank",{user:teacher,query:{courseId:course.id}});
    assert.ok(!r.body.data.some((row)=>Number(row.id)===Number(privateId)),"private bank entries are not shared");
    await db.query("UPDATE class_teachers SET status='revoked' WHERE live_class_id=$1 AND teacher_id=$2",[cls.id,stranger.id]);
    r=await invoke(assignments,"delete","/teacher/question-bank/:itemId",{user:stranger,params:{itemId:privateId}});
    assert.equal(r.statusCode,403,"revoked teacher must not mutate the old course bank");
    r=await invoke(assignments,"delete","/teacher/question-bank/:itemId",{user:admin,params:{itemId:privateId}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
  });
  await t.test("support case requires valid class owner and resolution outcome",async()=>{
    let r=await invoke(support,"post","/",{user:teacher,body:{classId:cls.id,userId:student.id,ownerId:teacher.id,note:"Contact learner to discuss missed lessons",status:"contacted"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));const id=r.body.data.id;
    r=await invoke(support,"put","/:id",{user:teacher,params:{id},body:{classId:cls.id,userId:student.id,ownerId:teacher.id,note:"Learner has attended tutoring",status:"resolved",outcome:""}});
    assert.equal(r.statusCode,422);
    r=await invoke(support,"put","/:id",{user:teacher,params:{id},body:{classId:cls.id,userId:student.id,ownerId:teacher.id,note:"Learner has attended tutoring",status:"resolved",outcome:"Learner completed the missing exercises"}});
    assert.equal(r.statusCode,200,JSON.stringify(r.body));
    r=await invoke(support,"get","/",{user:stranger,query:{classId:cls.id}});
    assert.equal(r.statusCode,403);
  });
});
