import { useCallback, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { fetchTeacherDashboardStats, fetchSupportCases, saveSupportCase } from "../../api/lmsClient";
import { panel,input,button,secondary,datetimeLocal } from "../components/workflowStyles";
const states={open:"Cần liên hệ",contacted:"Đã liên hệ",scheduled:"Đã hẹn hỗ trợ",resolved:"Đã hoàn tất"};
export default function StudentSupportPage(){
  const [params]=useSearchParams();
  const [classes,setClasses]=useState([]),[classId,setClassId]=useState(params.get("classId")||"");
  const [data,setData]=useState({students:[],owners:[],cases:[]}),[status,setStatus]=useState("all");
  const [editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  useEffect(()=>{fetchTeacherDashboardStats({limit:1}).then((r)=>{setClasses(r.data.classes||[]);setClassId((current)=>current||String(r.data.classes?.[0]?.id||""));}).catch((e)=>setError(e.message));},[]);
  const load=useCallback(async()=>{
    if(!classId)return;setLoading(true);setError("");
    try{const r=await fetchSupportCases(classId);setData(r.data);}catch(e){setError(e.message);setData({students:[],owners:[],cases:[]});}finally{setLoading(false);}
  },[classId]);
  useEffect(()=>{load();},[load]);
  const save=async(e)=>{
    e.preventDefault();setBusy(true);
    try{await saveSupportCase(editing.id,{...editing,classId,userId:Number(editing.userId),ownerId:Number(editing.ownerId),followUpAt:editing.followUpAt?new Date(editing.followUpAt).toISOString():null});setEditing(null);await load();toast.success("Đã cập nhật hồ sơ hỗ trợ.");}
    catch(err){toast.error(err.message);}finally{setBusy(false);}
  };
  return <div className="mx-auto max-w-5xl space-y-5 p-4 text-slate-900 dark:text-slate-100"><header><h1 className="text-2xl font-bold">Theo dõi hỗ trợ học viên</h1><p className="mt-1 text-sm text-slate-500">Ghi nhận liên hệ, người phụ trách, lịch hẹn và kết quả. Ghi chú chỉ dành cho đội ngũ phụ trách lớp.</p></header>
    <div className={panel+" flex flex-wrap gap-3"}><select aria-label="Chọn lớp" className={input+" sm:w-64"} value={classId} onChange={(e)=>{setClassId(e.target.value);setEditing(null);}}>{classes.map((c)=><option key={c.id} value={c.id}>{c.title}</option>)}</select><select aria-label="Trạng thái hỗ trợ" className={input+" sm:w-48"} value={status} onChange={(e)=>setStatus(e.target.value)}><option value="all">Tất cả trạng thái</option>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className={button} disabled={!data.students.length||loading} onClick={()=>setEditing({userId:params.get("studentId")||String(data.students[0]?.id||""),ownerId:String(data.owners[0]?.id||""),status:"open",note:"",outcome:"",followUpAt:""})}>Tạo hồ sơ hỗ trợ</button></div>
    {error&&<p role="alert" className="text-red-600">{error}</p>}
    {loading?<p>Đang tải...</p>:data.cases.filter((c)=>status==="all"||c.status===status).map((c)=><article key={c.id} className={panel+" space-y-2"}><div className="flex justify-between gap-3"><h2 className="font-semibold">{c.student_name}</h2><span className="text-sm">{states[c.status]}</span></div><p className="text-sm">Phụ trách: {c.owner_name}</p><p className="whitespace-pre-wrap text-sm">{c.note}</p>{c.follow_up_at&&<p className={"text-sm "+(c.status!=="resolved"&&new Date(c.follow_up_at)<new Date()?"font-semibold text-amber-600":"text-slate-500")}>Hẹn hỗ trợ: {new Date(c.follow_up_at).toLocaleString("vi-VN")}</p>}{c.outcome&&<p className="text-sm">Kết quả: {c.outcome}</p>}<p className="text-xs text-slate-500">Cập nhật {new Date(c.updated_at).toLocaleString("vi-VN")}</p><button className={secondary} onClick={()=>setEditing({id:c.id,userId:String(c.user_id),ownerId:String(c.owner_id),status:c.status,note:c.note,outcome:c.outcome||"",followUpAt:datetimeLocal(c.follow_up_at)})}>Cập nhật hồ sơ</button></article>)}
    {!loading&&!data.cases.some((c)=>status==="all"||c.status===status)&&<p className={panel}>Chưa có hồ sơ trong bộ lọc.</p>}
    {editing&&<div role="dialog" aria-modal="true" aria-label="Hồ sơ hỗ trợ" className="fixed inset-0 z-[80] overflow-y-auto bg-black/50 p-4"><form className={panel+" mx-auto my-6 max-w-xl space-y-4"} onSubmit={save}><h2 className="font-bold">{editing.id?"Cập nhật":"Tạo"} hồ sơ hỗ trợ</h2><label className="block text-sm">Học viên<select required disabled={Boolean(editing.id)} className={input} value={editing.userId} onChange={(e)=>setEditing({...editing,userId:e.target.value})}>{data.students.map((s)=><option key={s.id} value={s.id}>{s.name||s.email}</option>)}</select></label><label className="block text-sm">Người phụ trách<select required className={input} value={editing.ownerId} onChange={(e)=>setEditing({...editing,ownerId:e.target.value})}>{data.owners.map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="block text-sm">Trạng thái<select className={input} value={editing.status} onChange={(e)=>setEditing({...editing,status:e.target.value})}>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="block text-sm">Lịch hẹn / lần theo dõi tiếp<input type="datetime-local" required={editing.status==="scheduled"} className={input} value={editing.followUpAt} onChange={(e)=>setEditing({...editing,followUpAt:e.target.value})}/></label><label className="block text-sm">Nội dung liên hệ và kế hoạch<textarea required minLength={10} maxLength={2000} rows={3} className={input} value={editing.note} onChange={(e)=>setEditing({...editing,note:e.target.value})}/></label><label className="block text-sm">Kết quả hỗ trợ<textarea required={editing.status==="resolved"} minLength={editing.status==="resolved"?10:undefined} maxLength={2000} rows={3} className={input} value={editing.outcome} onChange={(e)=>setEditing({...editing,outcome:e.target.value})}/></label><div className="flex justify-end gap-2"><button disabled={busy} type="button" className={secondary} onClick={()=>setEditing(null)}>Hủy</button><button disabled={busy} className={button}>Lưu hồ sơ</button></div></form></div>}
  </div>;
}
